let constant = {
    TRUESTATUS: 1,
    FALSESTATUS: 0,
    MISSINGPARAMS: 'Please provide  params',
    MISSINGVEHCILE: 'Either missing VehicleID or (Address latitude or longitude) or UserId',
    MISSINGCONTACT: "Please provide both Country Code and Contact Number",
    MISSINGPARAMSORFILES: 'Either file or Params are missing',
    CHANGEPASSWORDLINK: 'Link for change password has been sent on your email',
    NOCONTACTS: 'Phone Number not associated with any account',
    TRUE: true,
    FALSE: false,
    NOTEXISTS: 'User doesnt exist',
    VEHCILEADDSUCEESS: "Vehicle added successfully",
    VERFIEDTRUE: 'Verfied Success',
    VERFIEDFALSE: 'tokens dont match',
    TRUEMSG: 'Successful',
    FALSEMSG: 'Please try again later',
    SENTMSG: 'Sent successfully',
    INVALIDPARAMS: 'Invalid parameters',
    BOOKSUCCESSFULL: 'Booking created successfully',
    ISSUESUCCESSFULLY: 'Issue created succefully',
    EMAILPASSWORDPARAMS: 'Provide both email and password',
    CODEUSED: 'Code already used',
    VERIFYMAIL: 'Verification Link has been sent on your mail',
    REMOVEFAV: 'Removed from favourites',
    NOTREGISTERED: 'This email not registered with any account',
    OWNERIDMISSING: "Owner Id missing",
    USERIDMISSING: "User Id missing",
    VEHCILEIDMISSING: "Vehicle Id missing",
    NOTVERIFIED: 'Not Verified yet',
    NOTADMINVERIFIED: 'Yet to be verified by admin',
    WRONGCODEUSED: 'Verification code is not correct.',
    EXISTSMSG: 'Email or Phone Number associated with another account',
    UNIQUEEMAILANDUSERNAME: 'Email or username already taken , Provide unique email and username',
    VERIFYPENDING: 'Your account verification pending.',
    VERIFYDENY: 'Your document verification declined',
    DISABLEACCOUNT: 'Your account is disable by admin',
    SOMETHINGWRONG: 'Something went wrong. Please try again later',
    NOTAUTHERIZED: 'You can not verify driver account',
    ADDMSG: 'Added successfully',
    UPDATEMSG: 'Updated sucessfully',
    ADDSUCCESS: 'Uploaded Successfully',
    ADDFAIL: 'Something went wrong while uploading',
    SAVEMSG: 'Saved sucessfully',
    ACCEPTREQUEST: 'Request Accepted',
    REQUESTDECLINE: 'Request Declined',
    DELETEMSG: 'Deleted sucessfully',
    NOFILEMSG: 'No file selected',
    SCHEDULEMSG: 'Booking schedule successfully',
    CARDALREADYADDED: 'Card already added',
    NOTAXINEARBY: 'No taxi available nearby, Please try after some time',
    LATEMSG: 'Oops you are late this time..',
    CANCELREQUESTMSG: 'Request Cancel by User',
    LIMIT: 30,
    INVALIDCODE: 'You have entered invalid code',
    DISABLECODE: 'Discount not available on this code',
    EXPIREDCODE: 'Promocode expired',
    ALREADYUSEDCODE: 'Promocode already Used',
    REACHEDCODELIMIT: 'You have reached usage limit,You can not used this code.',
    NOTSAMEPASSWORDS: "Passwords don't match",
    WRONGOLDPASS: 'Wrong Old Password',
    FILEMISSING: 'Files missing',
    WRONGCREDENTIALS: 'Wrong credentials',
    NOTVERIFIEDLOGIN: 'Sorry you can`t login. Verfiy first ',
    NOPASSWORDPROVIDED: 'Please Provide Password',
    SIGNUPSUCCESS: 'Account created Successfully',


    ERRORLOGINMESSAGE: 'Email or password is incorrect.',
    ERR: 'Something went wrong please try again later.',

}

module.exports = constant